// --------------------------------
// Guião 6, Ex.1
// Arquitectura de Computadores II
// Pedro Teixeira, 84715, MIECT
// --------------------------------

# include <detpic32.h>
# include "../Utils/utils.h"

# define  numSamples 4

// Interrupt Handler
void _int_(27) isr_adc(void) {
  // Debug
  // printf("\nEntering Interrupt Handler for ADC\n");

  // Read conversion result (ADC1BUF0 value) and print it
  printInt(ADC1BUF0, 16 | 3 << 16);
  delay(100);             // comment as necessary. used to make debugging easier
  putChar(' ');

  // Start conversion
  AD1CON1bits.ASAM = 1;

  // Reset AD1IF
  IFS1bits.AD1IF = 0;
}

int main(void) {
  // Configure port RB4 as analog input
  TRISBbits.TRISB4  = 1;   // RB4 digital output disconnected
  AD1PCFGbits.PCFG4 = 0;   // RB4 configured as analog input (AN4)

  // ADC Desired input analog channel (0 to 15)
  AD1CHSbits.CH0SA  = 4;

  configADC(numSamples);

  // Interrupt System
  // Step 1. Set Priority Level of the ADC Interrupts: value between 1 and 6 (7
  // is max priority and should NOT be used and 0 means no interrupts are accepted
  IPC6bits.AD1IP = 2;

  // Step 2. Authorize the interrupts generated by the ADC
  IEC1bits.AD1IE = 1;

  // Step 3. Reset ADC interrupt flag
  IFS1bits.AD1IF = 0;

  // Step 4. Global enable of the interrupt system
  EnableInterrupts();

  // Start conversion
  AD1CON1bits.ASAM = 1;

  // Empty program (the Interrupt Handler handles (:P) the interrupts from the ADC
  while (1) {

  }

  return 1;
}
